# Generated by Django 6.0.1 on 2026-01-24 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=150)),
                ('ownerVat', models.CharField(max_length=13)),
                ('ownerAddress', models.CharField(max_length=100)),
                ('ownerWorker', models.CharField(max_length=80)),
                ('ownerPermission', models.CharField(max_length=20)),
                ('ownerPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteName', models.CharField(max_length=120)),
                ('notePhone', models.CharField(max_length=20)),
                ('noteAddress', models.CharField(max_length=200)),
                ('noteCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('noteActivityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insecta.activity')),
            ],
        ),
    ]
