# Generated by Django 6.0.1 on 2026-01-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0002_rename_noteactivityname_note_noteactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityDescr',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='activity',
            name='activityURL',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='note',
            name='noteFinished',
            field=models.BooleanField(default=False),
        ),
    ]
