# Generated by Django 6.0.1 on 2026-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0003_activity_activitydescr_activity_activityurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='ownerMail',
            field=models.CharField(default='proinsekta@gmail.com', max_length=20),
        ),
    ]
