# Generated by Django 6.0.1 on 2026-01-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0004_owner_ownermail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='ownerMail',
            field=models.CharField(max_length=20),
        ),
    ]
