# Generated by Django 6.0.1 on 2026-01-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0005_alter_owner_ownermail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=150)),
                ('customerVat', models.CharField(max_length=13)),
                ('customerCity', models.CharField(max_length=100)),
                ('customerAddress', models.CharField(max_length=100)),
                ('customerMail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=150)),
                ('locationCity', models.CharField(max_length=100)),
                ('locationAddress', models.CharField(max_length=100)),
                ('locationMail', models.CharField(max_length=20)),
                ('locationCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insecta.customer')),
            ],
        ),
    ]
