# Generated by Django 6.0.1 on 2026-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0006_customer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerPostCode',
            field=models.SmallIntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='location',
            name='locationPostCode',
            field=models.SmallIntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='owner',
            name='ownerPostCode',
            field=models.SmallIntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerMail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationMail',
            field=models.CharField(max_length=50),
        ),
    ]
