# Generated by Django 6.0.1 on 2026-01-25 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0007_customer_customerpostcode_location_locationpostcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractPrice', models.IntegerField()),
                ('contractStart', models.DateField(default=django.utils.timezone.now)),
                ('contractValid', models.BooleanField(default=True)),
                ('contractFrequencyMonth', models.IntegerField(default=3)),
                ('contractLocationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insecta.location')),
                ('contractServiceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insecta.service')),
            ],
        ),
    ]
