# Generated by Django 6.0.1 on 2026-01-25 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0008_service_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobPrice', models.IntegerField()),
                ('jobStart', models.DateField(default=django.utils.timezone.now)),
                ('jobLocationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insecta.location')),
                ('jobServiceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insecta.service')),
            ],
        ),
    ]
