# Generated by Django 6.0.1 on 2026-01-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0009_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobURL',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='locationtyURL',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
    ]
