# Generated by Django 6.0.1 on 2026-02-21 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0011_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='noteFinished',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='jobcontractId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.contract'),
        ),
        migrations.AddField(
            model_name='note',
            name='contact_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insecta.contactmessage'),
        ),
        migrations.AddField(
            model_name='note',
            name='noteEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='noteMessage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('in_progress', 'Folyamatban'), ('done', 'Kész')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityURL',
            field=models.ImageField(blank=True, default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insecta.activity'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractLocationName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.location'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractServiceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.service'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerAddress',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerCity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerMail',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerVat',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobLocationName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobServiceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.service'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobURL',
            field=models.ImageField(blank=True, default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationAddress',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationCity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationCustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.customer'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationMail',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationtyURL',
            field=models.ImageField(blank=True, default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='noteActivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.activity'),
        ),
        migrations.AlterField(
            model_name='note',
            name='noteAddress',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerAddress',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerMail',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerPermission',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerPhone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerVat',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerWorker',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
