# Generated by Django 6.0.1 on 2026-02-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0012_remove_note_notefinished_contactmessage_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityURL1',
            field=models.ImageField(blank=True, default=' ', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activityURL2',
            field=models.ImageField(blank=True, default=' ', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activityURL3',
            field=models.ImageField(blank=True, default=' ', upload_to='images/'),
        ),
    ]
