# Generated by Django 6.0.1 on 2026-02-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0013_activity_activityurl1_activity_activityurl2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobCustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.customer'),
        ),
    ]
