# Generated by Django 6.0.1 on 2026-02-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0014_job_jobcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contractCustomerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insecta.customer'),
        ),
    ]
