# Generated by Django 6.0.1 on 2026-02-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0015_contract_contractcustomername'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobRemark',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
