# Generated by Django 6.0.1 on 2026-02-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0016_job_jobremark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['jobLocationName', '-jobStart']},
        ),
    ]
