# Generated by Django 6.0.1 on 2026-03-18 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0017_alter_job_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=150)),
                ('ownerVat', models.CharField(blank=True, default='', max_length=13)),
                ('ownerPostCode', models.SmallIntegerField(default=4000)),
                ('ownerAddress', models.CharField(blank=True, default='', max_length=100)),
                ('ownerWorker', models.CharField(blank=True, default='', max_length=80)),
                ('ownerPermission', models.CharField(blank=True, default='', max_length=20)),
                ('customer_id', models.IntegerField(default=0)),
                ('customerName', models.CharField(max_length=150)),
                ('customerVat', models.CharField(blank=True, default='', max_length=13)),
                ('customerPostCode', models.SmallIntegerField(default=4000)),
                ('customerCity', models.CharField(blank=True, default='', max_length=100)),
                ('customerAddress', models.CharField(blank=True, default='', max_length=100)),
                ('location_id', models.IntegerField(default=0)),
                ('locationPostCode', models.SmallIntegerField(default=4000)),
                ('locationCity', models.CharField(blank=True, default='', max_length=100)),
                ('locationAddress', models.CharField(blank=True, default='', max_length=100)),
                ('service_id', models.IntegerField(default=0)),
                ('serviceName', models.CharField(max_length=120)),
                ('contractStart', models.DateField(default=django.utils.timezone.now)),
                ('contractFrequencyMonth', models.IntegerField(default=3)),
                ('jobStart', models.DateField(default=django.utils.timezone.now)),
                ('jobToDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
