# Generated by Django 6.0.1 on 2026-03-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0018_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='contract_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='jobMonth',
            field=models.IntegerField(default=0),
        ),
    ]
