# Generated by Django 6.0.1 on 2026-03-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0019_todo_contract_id_todo_jobmonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
