# Generated by Django 6.0.3 on 2026-03-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0020_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationtyURL',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
