# Generated by Django 6.0.3 on 2026-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0021_alter_location_locationtyurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locationLat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='locationLng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
