# Generated by Django 6.0.3 on 2026-03-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0022_location_locationlat_location_locationlng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='locationtyURL',
            new_name='locationURL',
        ),
    ]
