# Generated by Django 6.0.3 on 2026-04-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insecta', '0023_rename_locationtyurl_location_locationurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['locationName']},
        ),
    ]
